# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    security.authentication.success_handler:
        class: HuCap\UsuariosBundle\Service\AuthenticationSuccessHandler
        arguments: ["@security.http_utils"]
        calls:
            - [ setContainer, [ "@service_container" ] ]
    
    my.oauth_aware.user_provider.service:
        class: HuCap\UsuariosBundle\Security\Core\User\FOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - google: googleId
              linkedin: linkedinId